server:
  port: 9010
spring:
  application:
    name: pay
  rabbitmq:
    host: 192.168.140.150
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
weixin:
  appid: wx8397f8696b538317
  partner: 1473426802
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notifyUrl: http://y3l2461659.zicp.vip/wxpay/notify #回调地址

# Self-definition
mq:
  pay:
    queue:
      seckill: queue.seckillqueue
      basically: queue.basicallyqueue
    exchange:
      seckill: exchange.seckillqueue
      basically: exchange.basicallyqueue
    routingKey:
      seckill: queue.seckillqueue
      basically: queue.basicallyqueue